version: '3.8'

services:
  web_portfolio:
    build:
      context: ./docker
      dockerfile: web_portfolio/Dockerfile
    ports:
      - ${DOCKER_WEB_PORTFOLIO_HOST_PORT}:5050
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/salehrashid/portfolio-saleh
